name: Publish
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  deploy:
    uses: "geoffrevanwyk/geoffreyvanwyk.dev/.github/workflows/pelican.yml@master"
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    with:
      settings: "publishconf.py"